## Numpy Array Operations

In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Basic Slicing {arr[2:7]}")

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(f"2d array Specific element slicing:\n {arr_2d[1,2]}")
print(f"2d array Specific row slicing:\n {arr_2d[1]}")
print(f"2d array Specific column slicing:\n {arr_2d[:,1]}")

Basic Slicing [3 4 5 6 7]
2d array Specific element slicing:
 6
2d array Specific row slicing:
 [4 5 6]
2d array Specific column slicing:
 [2 5 8]


## Numpy Array Sorting

In [16]:
arr=np.array([3,2,56,79,13,5])
print(f"sorted array {np.sort(arr)}")

arr_2d = np.array([[5,2],
                   [8,3],
                   [4,1]
                   ])

print(f"Sorted 2d Array {np.sort(arr_2d,axis=0)}")


sorted array [ 2  3  5 13 56 79]
Sorted 2d Array [[4 1]
 [5 2]
 [8 3]]


## Filtering

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,0])
print(f"Even numbers from the given array are{number[number%2 == 0]}")


Even numbers from the given array are[2 4 6 8 0]


## Filter with mask

In [18]:
mask = number %2 == 0
even_no = np.array([1,2,3,4,5,6,7,8,9,0])
print(f"Using mask it looks like this {even_no[mask]}")

Using mask it looks like this [2 4 6 8 0]


## Indexing and Where Clause

In [23]:
indices = [0,2,4,6]
print(even_no[indices])

where_result= np.where(even_no > 5)
print(f"Here is the result for the where clause part {even_no[where_result]}")


condition_array =np.where(even_no >5 , even_no *2 , even_no* 10)
print(f"The conditional based array is {condition_array}")

[1 3 5 7]
Here is the result for the where clause part [6 7 8 9]
The conditional based array is [10 20 30 40 50 12 14 16 18  0]


## Merging two Numpy arrays

In [24]:
arr1 = np.array([1,2,3])
arr2=np.array([3,4,5])

merged= np.concatenate((arr1,arr2))
print(merged)

[1 2 3 3 4 5]


## Array compatibility

In [25]:
a=np.array([1,2,3])
b=np.array([2,3,4])

print(f"Compatibility checker {a.shape == b.shape}")

Compatibility checker True


## Adding rows and column

In [28]:
og= np.array([[1,5],[7,2]])
new_row = np.array([4,1])

print(f"The new added row {np.vstack((og,new_row))}")

new_col = np.array([[7,8],[9,0]])
print(f"The new added column {np.hstack((og,new_col))}")


The new added row [[1 5]
 [7 2]
 [4 1]]
The new added column [[1 5 7 8]
 [7 2 9 0]]


## Deleting in Numpy

In [31]:
delete = np.array([12,3,4,5,6,7,8])
deleted_arr = np.delete(delete,6)
print((f"The array after deletion is {deleted_arr}"))

The array after deletion is [12  3  4  5  6  7]
