##Numpy array and basics

In [2]:
import numpy as np

## Creating Numpy arrays from list

In [3]:
arr_1d=  np.array([1,2,3,4,5])
print(f"This is 1d array {arr_1d}")

arr_2d=np.array([[1,2,3],[4,5,6]])
print(f"This is 2d array{arr_2d}")

This is 1d array [1 2 3 4 5]
This is 2d array[[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [7]:
py_list = [1,2,3]
print(f"List multiplication {py_list *2}")

np_arr = np.array([1,2,3])
print(f"Numpy array multiplication {np_arr *2}")

import time

start=time.time()
li=[i*2 for i in range(1000000)]
print(f"Calculation time for list mul is: {time.time() - start}")

startnp=time.time()
arr=np.arange(1000000)*2
print(f"Calculation time for arr mul is: {time.time() - startnp}")


List multiplication [1, 2, 3, 1, 2, 3]
Numpy array multiplication [2 4 6]
Calculation time for list mul is: 0.07363629341125488
Calculation time for arr mul is: 0.017532825469970703


## Creating Arrays in numpy from scratch

In [10]:
zeros_arr  = np.zeros((3,3))
print(f"The array of zeros \n {zeros_arr}")

ones_arr  = np.ones((3,3))
print(f"The array of ones \n {ones_arr}")

constant_arr = np.full((3,3),7)
print(f"The array of contant \n {constant_arr}")

random_arr = np.random.random((3,4))
print(f"The random array from numpy is \n{random_arr}")


The array of zeros 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The array of ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The array of contant 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
The random array from numpy is 
[[0.08071289 0.3456268  0.87126512 0.55095018]
 [0.20116085 0.27918514 0.90085284 0.90153506]
 [0.41642232 0.19665162 0.43138899 0.47244898]]
